### ISSUE TITLE
initramfs_files.tar.gz should not be a tarball

### ISSUE THREAD

**Issue by bell07** [Linux-4-Switch/bootstack#2]
I propose the initramfs_files.tar.gz should be an extracted folder instead of tarball in this repo. This make it easier to track changes and propose improvements. git is able to store execution flag for binaries.

**Comment by bell07** [comment]
I think the tarbal should be removed after this change, to avoid redundancy

**Comment by bell07** [comment]
Ok, see the issue with empty folders are lost in repo :-(

**Comment by bell07** [comment]
Git ignores empty folders. dev, mnt, proc, sys, tmp, var are missed.
The build_initramfs.sh needs to add this empty folders to the initramfs in other way.

**Comment by Azkali** [comment]
closed by 808fc43
